---
deployment:
      tasks:
        - export DEPLOYPATH=/home/u3932491/public_html/OBE_API  # Add /<app_folder> if required
        # - /bin/cp index.php $DEPLOYPATH                 #Copy specific file to destination from root
        # - /bin/cp /<sub_folder>/<file_name> $DEPLOYPATH   #copy specific file from source sub folder
        # - /bin cp * $DEPLOYPATH                           #copy all from root 
        # - /bin cp /<sub_folder>/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH    